import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'
import {
  MAX_TIER_OPTIONS,
  STEP_LABELS,
  UNANNOTATED_OPTIONS,
  blockedProfileAction,
  credentialCta,
  credentialLabel,
  modeLabel,
  profileSourceLabel,
  reasonText,
} from '@/utils/profiles'
import { accessReasonLabel } from '@/utils/accessReason'

// Spec 108-l (FR-052, L5/L6): the enum value sets of internal/profile/contract.go
// (enums.json, generated by a Go test) must equal the generated contracts.ts,
// and the words the Web UI shows for every value must equal labels.json, the
// same table macOS is pinned to (ProfilesEnumsLabelsTests.swift).

const CONTRACT_DIR = resolve(__dirname, '../../../internal/profile/testdata/contract')
const enums: Record<string, string[]> = JSON.parse(readFileSync(resolve(CONTRACT_DIR, 'enums.json'), 'utf8'))
const labels = JSON.parse(readFileSync(resolve(CONTRACT_DIR, 'labels.json'), 'utf8')) as Record<string, any>
const contractsTs = readFileSync(resolve(__dirname, '../../src/types/contracts.ts'), 'utf8')

// Every exported string constant, exactly as the generator writes it:
//   export const Name = 'value' as const;
// (an exact-line match: a substring check would pass on a comment or a typo).
const CONSTS = new Map<string, string>()
for (const match of contractsTs.matchAll(/^export const (\w+) = '([^']*)' as const;$/gm)) {
  CONSTS.set(match[1], match[2])
}

// family -> the constant-name prefix the generator uses for it, minus the
// prefixes that belong to another family.
const TS_FAMILIES: Record<string, { prefix: string; exclude?: string[] }> = {
  unannotated: { prefix: 'Unannotated' },
  reason: { prefix: 'ProfileReason' },
  source: { prefix: 'ProfileSource' },
  block_reason: { prefix: 'BlockReasonProfile' },
  explain_step: { prefix: 'ExplainStep', exclude: ['ExplainStepStatus'] },
  fix_action: { prefix: 'FixAction' },
  credential_state: { prefix: 'CredentialState' },
  warning_severity: { prefix: 'WarningSeverity' },
  explain_verdict: { prefix: 'ExplainVerdict' },
  change_kind: { prefix: 'ProfileChange' },
  rotation_state: { prefix: 'Rotation' },
  surface: { prefix: 'ProfileSurface' },
  warning_code: { prefix: 'Warning', exclude: ['WarningSeverity', 'WarningAction'] },
  error_code: { prefix: 'ErrorCode' },
  credential_error_code: { prefix: 'CredentialErrorCode' },
  guard_fix: { prefix: 'GuardFix' },
}

function tsValues(family: string): string[] {
  const { prefix, exclude = [] } = TS_FAMILIES[family]
  return [...CONSTS.entries()]
    .filter(([name]) => name.startsWith(prefix) && !exclude.some(skip => name.startsWith(skip)))
    .map(([, value]) => value)
    .sort()
}

describe('enums.json equals the generated contracts.ts (FR-052)', () => {
  it('reads the constants it compares against', () => {
    expect(CONSTS.size).toBeGreaterThan(60)
  })

  for (const family of Object.keys(TS_FAMILIES)) {
    it(`${family}: the TypeScript constants are exactly the Go values`, () => {
      expect(enums[family], `enums.json has no ${family}`).toBeDefined()
      expect(tsValues(family)).toEqual([...enums[family]].sort())
    })
  }

  it('the comparison can fail: a missing value is a difference', () => {
    expect(tsValues('surface')).not.toEqual([...enums.surface, 'not_a_surface'].sort())
  })
})

describe('the Web UI words equal labels.json (L6, US3-3)', () => {
  it('access reasons: reasonText and accessReasonLabel return the table for every value', () => {
    expect(Object.keys(labels.access_reason).sort()).toEqual([...enums.access_reason].sort())
    for (const [reason, word] of Object.entries<string>(labels.access_reason)) {
      expect(reasonText(reason), reason).toBe(word)
      expect(accessReasonLabel(reason, { disabled: false }), reason).toBe(word)
    }
    expect(reasonText('')).toBe(labels.access_reason_none)
    expect(reasonText(undefined)).toBe(labels.access_reason_none)
  })

  it('tool_approval reads Disabled only for an operator-disabled tool', () => {
    expect(accessReasonLabel('tool_approval', { disabled: true })).toBe('Disabled')
  })

  it('sources: profileSourceLabel returns the table for every value', () => {
    for (const source of enums.source) {
      expect(profileSourceLabel(source), source).toBe(labels.source[source])
    }
  })

  it('explain steps: STEP_LABELS has the table, nothing more', () => {
    expect(STEP_LABELS).toEqual(labels.explain_step)
  })

  it('credential states: credentialLabel returns the table for every value', () => {
    for (const state of enums.credential_state) {
      expect(credentialLabel(state), state).toBe(labels.credential_state[state])
    }
  })

  it('credential CTA: credentialCta returns the table for every state, empty only for a client credential', () => {
    expect(Object.keys(labels.credential_cta).sort()).toEqual([...enums.credential_state].sort())
    for (const state of enums.credential_state) {
      if (state === 'client') {
        expect(labels.credential_cta[state]).toBe('')
        continue
      }
      expect(credentialCta(state), state).toBe(labels.credential_cta[state])
    }
    // a state the Web UI has never heard of is not an upgrade either
    expect(credentialCta(undefined)).toBe(labels.credential_cta.unknown)
  })

  it('binding modes: modeLabel returns the table for every value', () => {
    for (const mode of enums.binding_mode) {
      expect(modeLabel(mode), mode).toBe(labels.binding_mode[mode])
    }
  })

  it('unannotated handling: the editor options are the table', () => {
    expect(Object.fromEntries(UNANNOTATED_OPTIONS.map(option => [option.value, option.label]))).toEqual(labels.unannotated)
  })

  it('tier cap: the editor options are the table (plus "No cap")', () => {
    const capped = MAX_TIER_OPTIONS.filter(option => option.value !== '')
    expect(Object.fromEntries(capped.map(option => [option.value, option.label]))).toEqual(labels.max_tier)
  })

  it('blocked-row action: a server outside the profile opens the profile editor', () => {
    expect(blockedProfileAction('profile_server_scope')).toBe('open')
    expect(blockedProfileAction('profile_tier')).toBe('allow')
    expect(blockedProfileAction(undefined)).toBeNull()
  })
})
