version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: linux
    main: ./cmd/mcpproxy
    binary: mcpproxy
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: windows
    main: ./cmd/mcpproxy
    binary: mcpproxy
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

  - id: darwin
    main: ./cmd/mcpproxy
    binary: mcpproxy
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: linux
    builds: ["linux"]
    name_template: "mcpproxy-{{ .Version }}-linux-amd64"
    files:
      - README.md
      - assets/**/*
    
  - id: windows
    builds: ["windows"]
    name_template: "mcpproxy-{{ .Version }}-windows-amd64"
    files:
      - README.md
      - assets/**/*
    
  - id: darwin
    builds: ["darwin"]
    name_template: "mcpproxy-{{ .Version }}-darwin-{{ .Arch }}"
    files:
      - README.md
      - assets/**/*

release:
  github:
    owner: smart-mcp-proxy
    name: mcpproxy-go
  draft: false
  prerelease: auto
  name_template: "mcpproxy {{ .Tag }}"
  header: |
    ## mcpproxy {{ .Tag }}
    
    Smart MCP Proxy - Intelligent tool discovery and proxying for Model Context Protocol servers.
    
  footer: |
    ### Installation
    
    #### Download and Run
    1. Download the appropriate archive for your platform
    2. Extract the binary
    3. Run `mcpproxy` to start with system tray, or `mcpproxy --tray=false` for headless mode
    
    #### Platform-specific notes:
    - **macOS**: Full system tray support with menu and icons
    - **Windows**: Full system tray support with menu and icons  
    - **Linux**: Headless mode only (no system tray due to compatibility)

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge conflict"
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch 