package server

import (
	"reflect"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"

	"github.com/smart-mcp-proxy/mcpproxy-go/internal/config"
)

// The input schema of the `profiles` admin tool (Spec 108-h, H7). The profile
// properties are generated by reflection from config.ProfileConfig's JSON tags,
// so the tool cannot drift from the REST body: a field added to ProfileConfig
// appears on MCP with the same name and type, and a test pins the property set.

// profilesOperations is the `operation` enum, in documentation order.
var profilesOperations = []string{
	"list", "get", "create", "update", "delete", "rename", "classify", "assign",
	"list_clients", "effective_tools", "explain",
}

// profilesMutatingOps are the operations that write profiles, bindings or
// tokens. Each calls the FR-008a guard before writing and is refused under
// read_only_mode and disable_management.
var profilesMutatingOps = map[string]bool{
	"create": true, "update": true, "delete": true, "rename": true, "classify": true, "assign": true,
}

// profilesOpArgs are the arguments beyond the ProfileConfig fields (REST field
// and query names). Their descriptions are one line each: the schema is listed
// for every administrator session, so its size is tool-surface cost (H13).
var profilesOpArgs = []struct {
	name string
	desc string
	enum []string
	typ  string
}{
	{name: "new_name", typ: "string", desc: "rename: the new profile name."},
	{name: "reassign_to", typ: "string", desc: "delete: another existing profile that takes over the clients and tokens."},
	{name: "force", typ: "boolean", desc: "delete: delete although in use, leaving pins dangling (never overrides the anonymous_profile)."},
	{name: "tool", typ: "string", desc: "classify, explain: upstream tool as server:tool."},
	{name: "tier", typ: "string", enum: []string{"read", "write", "destructive", ""}, desc: "classify: tier to assign; \"\" removes the classification."},
	{name: "client", typ: "string", desc: "assign, explain, effective_tools, list_clients: client id."},
	{name: "profile", typ: "string", desc: "assign: profile to bind (\"\" = All servers). explain, list_clients: profile name (list_clients \"-\" = All servers)."},
	{name: "mode", typ: "string", enum: []string{"locked", "switchable"}, desc: "assign: binding mode; omitted keeps the current mode (profile \"\" is switchable)."},
	{name: "from_profile", typ: "string", desc: "assign (bulk): move every client bound to this profile (\"\" = All servers)."},
	{name: "to_profile", typ: "string", desc: "assign (bulk): the profile they move to (\"\" = All servers)."},
	{name: "token", typ: "string", desc: "explain: regular agent token name."},
	{name: "anonymous", typ: "boolean", desc: "explain: explain a caller with no credential."},
	{name: "server", typ: "string", desc: "effective_tools: keep only this server's rows."},
	{name: "reason", typ: "string", desc: "effective_tools: keep only rows with this access reason."},
}

// profileConfigDescriptions are the one-line descriptions of the ProfileConfig
// properties. A field without an entry still appears, with a generic line.
var profileConfigDescriptions = map[string]string{
	"name":             "get, create, update, delete, rename, classify, effective_tools: the profile name (update replaces the profile with this name).",
	"servers":          "create, update: servers the profile reaches (all servers when empty).",
	"title":            "create, update: display title, at most 80 characters.",
	"description":      "create, update: description, at most 500 characters.",
	"max_tier":         "create, update: highest tool tier the profile allows; omitted = no cap.",
	"unannotated":      "create, update: handling of tools with no tier hint; omitted = deny under a read/write cap.",
	"tools":            "create, update: tool rules: allow/deny are server:tool globs (deny wins), classify maps an exact server:tool to a tier.",
	"code_execution":   "create, update: false turns code_execution off for the profile; omitted inherits.",
	"management_tools": "create, update: true makes the management tools (upstream_servers, quarantine_security, profiles) visible under it; omitted inherits.",
	"switchable_to":    "create, update: profile names a session may set_profile into; [] = none, omitted = unset.",
}

// profileConfigSchemaOverrides pin the enumerations the Go types cannot carry.
var profileConfigSchemaOverrides = map[string]func(schema map[string]any){
	"max_tier":    func(s map[string]any) { s["enum"] = []string{"read", "write", "destructive"} },
	"unannotated": func(s map[string]any) { s["enum"] = []string{"deny", "as_write", "as_read"} },
	"tools": func(s map[string]any) {
		props, _ := s["properties"].(map[string]any)
		if classify, ok := props["classify"].(map[string]any); ok {
			classify["additionalProperties"] = map[string]any{"type": "string", "enum": []string{"read", "write", "destructive"}}
		}
	},
}

// profileConfigJSONFields lists the JSON property names of config.ProfileConfig
// in declaration order (the source of truth for the tool's profile properties).
func profileConfigJSONFields() []string {
	t := reflect.TypeOf(config.ProfileConfig{})
	out := make([]string, 0, t.NumField())
	for i := 0; i < t.NumField(); i++ {
		if name := jsonFieldName(t.Field(i)); name != "" {
			out = append(out, name)
		}
	}
	return out
}

func jsonFieldName(f reflect.StructField) string {
	tag := f.Tag.Get("json")
	if tag == "-" || !f.IsExported() {
		return ""
	}
	name, _, _ := strings.Cut(tag, ",")
	if name == "" {
		return f.Name
	}
	return name
}

// jsonSchemaForType renders the JSON schema of a Go type the way encoding/json
// sees it: pointers are transparent, a slice is an array, a map with string
// values is an object, a struct is an object of its JSON-tagged fields.
func jsonSchemaForType(t reflect.Type) map[string]any {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	switch t.Kind() {
	case reflect.Bool:
		return map[string]any{"type": "boolean"}
	case reflect.String:
		return map[string]any{"type": "string"}
	case reflect.Int, reflect.Int32, reflect.Int64, reflect.Uint, reflect.Uint32, reflect.Uint64:
		return map[string]any{"type": "integer"}
	case reflect.Float32, reflect.Float64:
		return map[string]any{"type": "number"}
	case reflect.Slice:
		return map[string]any{"type": "array", "items": jsonSchemaForType(t.Elem())}
	case reflect.Map:
		return map[string]any{"type": "object", "additionalProperties": jsonSchemaForType(t.Elem())}
	case reflect.Struct:
		props := map[string]any{}
		for i := 0; i < t.NumField(); i++ {
			if name := jsonFieldName(t.Field(i)); name != "" {
				props[name] = jsonSchemaForType(t.Field(i).Type)
			}
		}
		return map[string]any{"type": "object", "properties": props}
	}
	return map[string]any{}
}

// profilesToolProperties builds every property of the tool's input schema: the
// ProfileConfig fields (reflected) plus operation and the operation arguments.
func profilesToolProperties() map[string]map[string]any {
	props := map[string]map[string]any{}
	t := reflect.TypeOf(config.ProfileConfig{})
	for i := 0; i < t.NumField(); i++ {
		name := jsonFieldName(t.Field(i))
		if name == "" {
			continue
		}
		schema := jsonSchemaForType(t.Field(i).Type)
		if override := profileConfigSchemaOverrides[name]; override != nil {
			override(schema)
		}
		desc := profileConfigDescriptions[name]
		if desc == "" {
			desc = "create, update: profile field " + name + "."
		}
		schema["description"] = desc
		props[name] = schema
	}
	for _, a := range profilesOpArgs {
		schema := map[string]any{"type": a.typ, "description": a.desc}
		if a.enum != nil {
			schema["enum"] = a.enum
		}
		props[a.name] = schema
	}
	props["operation"] = map[string]any{
		"type": "string", "enum": profilesOperations,
		"description": "What to do. Every operation returns the data of its REST route.",
	}
	return props
}

// profilesToolOptions is the tool's option set: properties plus the required
// `operation`.
func profilesToolOptions() []mcp.ToolOption {
	props := profilesToolProperties()
	return []mcp.ToolOption{func(t *mcp.Tool) {
		if t.InputSchema.Properties == nil {
			t.InputSchema.Properties = map[string]any{}
		}
		for name, schema := range props {
			t.InputSchema.Properties[name] = schema
		}
		t.InputSchema.Required = append(t.InputSchema.Required, "operation")
	}}
}
