package main

import (
	"archive/tar"
	"archive/zip"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"
)

// update_apply.go holds the mechanical half of `mcpproxy update`'s self-update
// (Spec 092 FR-021): integrity verification, archive extraction, and the
// atomic binary swap. It is deliberately free of cobra and of network code so
// every rule below is unit-testable against real files in a t.TempDir().

const (
	// maxArchiveMemberBytes bounds a single extracted archive member. The core
	// binary is ~60-90 MB; the cap exists so a malicious archive cannot fill
	// the disk before the checksum comparison would have rejected it.
	maxArchiveMemberBytes = 512 << 20

	// verifyExecTimeout bounds the post-swap `<new binary> --version` probe
	// (FR-021: success means the new binary actually runs).
	verifyExecTimeout = 30 * time.Second
)

// parseChecksums parses a sha256sum-format manifest ("<hex>  <name>" or
// "<hex> *<name>") into name -> lowercase hex digest. Unparseable lines are
// skipped rather than failing the whole file: the manifest is generated by CI
// and a future extra line must not break verification of the entry we need.
func parseChecksums(r io.Reader) (map[string]string, error) {
	data, err := io.ReadAll(io.LimitReader(r, 4<<20))
	if err != nil {
		return nil, fmt.Errorf("read checksums: %w", err)
	}
	out := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		digest := strings.ToLower(fields[0])
		if len(digest) != 64 {
			continue
		}
		if _, err := hex.DecodeString(digest); err != nil {
			continue
		}
		name := strings.TrimPrefix(fields[len(fields)-1], "*")
		name = strings.TrimPrefix(name, "./")
		out[name] = digest
	}
	if len(out) == 0 {
		return nil, errors.New("checksums manifest contains no usable entries")
	}
	return out, nil
}

// verifyFileSHA256 hard-fails unless path hashes to wantHex.
func verifyFileSHA256(path, wantHex string) error {
	f, err := os.Open(path) // #nosec G304 -- path is a file this process just downloaded into its own temp dir
	if err != nil {
		return fmt.Errorf("open downloaded artifact: %w", err)
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return fmt.Errorf("hash downloaded artifact: %w", err)
	}
	got := hex.EncodeToString(h.Sum(nil))
	if !strings.EqualFold(got, wantHex) {
		return fmt.Errorf("checksum mismatch for %s: manifest says %s, download is %s (nothing was installed)",
			filepath.Base(path), wantHex, got)
	}
	return nil
}

// extractBinary pulls the single archive member named memberName (matched on
// base name, so a future archive that nests files still works) into destPath,
// which is created with mode 0o700 — the caller re-applies the real mode when
// swapping it into place.
func extractBinary(archivePath, memberName, destPath string) error {
	switch {
	case strings.HasSuffix(archivePath, ".zip"):
		return extractFromZip(archivePath, memberName, destPath)
	case strings.HasSuffix(archivePath, ".tar.gz"), strings.HasSuffix(archivePath, ".tgz"):
		return extractFromTarGz(archivePath, memberName, destPath)
	default:
		return fmt.Errorf("unsupported archive format: %s", filepath.Base(archivePath))
	}
}

func extractFromTarGz(archivePath, memberName, destPath string) error {
	f, err := os.Open(archivePath) // #nosec G304 -- self-downloaded temp file
	if err != nil {
		return fmt.Errorf("open archive: %w", err)
	}
	defer f.Close()

	gz, err := gzip.NewReader(f)
	if err != nil {
		return fmt.Errorf("open gzip stream: %w", err)
	}
	defer gz.Close()

	tr := tar.NewReader(gz)
	for {
		hdr, err := tr.Next()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return fmt.Errorf("read archive: %w", err)
		}
		if hdr.Typeflag != tar.TypeReg || filepath.Base(hdr.Name) != memberName {
			continue
		}
		return writeMember(tr, destPath)
	}
	return fmt.Errorf("archive does not contain %q", memberName)
}

func extractFromZip(archivePath, memberName, destPath string) error {
	zr, err := zip.OpenReader(archivePath)
	if err != nil {
		return fmt.Errorf("open archive: %w", err)
	}
	defer zr.Close()

	for _, entry := range zr.File {
		if entry.FileInfo().IsDir() || filepath.Base(entry.Name) != memberName {
			continue
		}
		rc, err := entry.Open()
		if err != nil {
			return fmt.Errorf("open archive member: %w", err)
		}
		defer rc.Close()
		return writeMember(rc, destPath)
	}
	return fmt.Errorf("archive does not contain %q", memberName)
}

// writeMember copies at most maxArchiveMemberBytes from r into destPath.
func writeMember(r io.Reader, destPath string) error {
	out, err := os.OpenFile(destPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC|os.O_EXCL, 0o700) // #nosec G304 -- destPath is our own temp path
	if err != nil {
		return fmt.Errorf("create staged binary: %w", err)
	}
	written, err := io.Copy(out, io.LimitReader(r, maxArchiveMemberBytes+1))
	if err != nil {
		out.Close()
		return fmt.Errorf("write staged binary: %w", err)
	}
	if written > maxArchiveMemberBytes {
		out.Close()
		return fmt.Errorf("archive member exceeds the %d-byte limit", int64(maxArchiveMemberBytes))
	}
	if err := out.Sync(); err != nil {
		out.Close()
		return fmt.Errorf("flush staged binary: %w", err)
	}
	return out.Close()
}

// ensureTargetWritable reports why the binary cannot be replaced, naming the
// path and its owner. It never suggests (let alone performs) privilege
// escalation: a root-owned install belongs to whoever installed it (FR-022).
func ensureTargetWritable(target string) error {
	dir := filepath.Dir(target)

	probe, err := os.CreateTemp(dir, ".mcpproxy-update-probe-*")
	if err != nil {
		return fmt.Errorf(
			"cannot update %s: its directory %s is not writable by the current user (%s).\n"+
				"mcpproxy never escalates privileges. Either reinstall through whatever owns that path, "+
				"or install a copy somewhere you own (e.g. ~/.local/bin) and update that one",
			target, dir, describeOwner(dir))
	}
	name := probe.Name()
	probe.Close()
	if err := os.Remove(name); err != nil {
		return fmt.Errorf("cannot clean up write probe %s: %w", name, err)
	}
	return nil
}

// applyNewBinary swaps staged into target atomically (FR-021):
// rename target -> target.old, rename staged -> target, then prove the new
// binary runs. The previous binary is restored on any failure and only removed
// once verification passed. Callers must pass an already-resolved (symlink
// free) target so a symlinked launcher keeps pointing at the file we replace.
func applyNewBinary(target, staged string, verify func(path string) error) (err error) {
	mode := os.FileMode(0o755)
	if fi, statErr := os.Stat(target); statErr == nil {
		mode = fi.Mode().Perm()
	}
	if chmodErr := os.Chmod(staged, mode); chmodErr != nil {
		return fmt.Errorf("preserve file mode %o: %w", mode, chmodErr)
	}

	backup := target + ".old"
	// A leftover .old from an interrupted run must not block the rename.
	_ = os.Remove(backup)

	if renameErr := os.Rename(target, backup); renameErr != nil {
		return fmt.Errorf("move current binary aside: %w", renameErr)
	}

	restore := func() {
		_ = os.Remove(target)
		if restoreErr := os.Rename(backup, target); restoreErr != nil {
			// Nothing left to try; make the situation explicit so the user can
			// recover by hand instead of discovering a missing binary later.
			fmt.Fprintf(os.Stderr,
				"CRITICAL: failed to restore the previous binary. It is at %s — move it back to %s manually: %v\n",
				backup, target, restoreErr)
		}
	}

	if renameErr := os.Rename(staged, target); renameErr != nil {
		restore()
		return fmt.Errorf("install new binary: %w", renameErr)
	}

	if verify != nil {
		if verifyErr := verify(target); verifyErr != nil {
			restore()
			return fmt.Errorf("new binary failed verification, previous version restored: %w", verifyErr)
		}
	}

	// Only now is the old binary expendable (FR-021).
	if rmErr := os.Remove(backup); rmErr != nil {
		// Non-fatal: the update succeeded, there is just a stale .old file.
		fmt.Fprintf(os.Stderr, "note: could not remove %s: %v\n", backup, rmErr)
	}
	return nil
}

// verifyInstalledVersion runs `<path> --version` and requires the output to
// mention wantVersion. FR-021: "success" is the new binary executing and
// reporting the expected version, not merely a rename returning nil.
func verifyInstalledVersion(path, wantVersion string) error {
	ctx, cancel := context.WithTimeout(context.Background(), verifyExecTimeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, path, "--version") // #nosec G204 -- path is the binary we just installed at a caller-resolved location
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("running %s --version failed: %w (output: %s)",
			filepath.Base(path), err, strings.TrimSpace(string(out)))
	}
	got := strings.TrimSpace(string(out))
	if !strings.Contains(got, strings.TrimPrefix(wantVersion, "v")) {
		return fmt.Errorf("installed binary reports %q, expected version %s", got, wantVersion)
	}
	return nil
}
