package updatecheck

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// checksums.go holds the release-artifact integrity primitives shared by every
// self-update path: `mcpproxy update --self` (cmd/mcpproxy) and the tray's
// GitHub self-update (internal/tray). They live here — a plain, build-tag-free
// package both can import — rather than being duplicated, because a second copy
// of security-critical parsing is a second thing to get wrong.

// maxChecksumsManifestBytes bounds the manifest read. A release manifest lists
// a few dozen artifacts; the cap keeps a hostile response from being read into
// memory unbounded. Hitting the cap is an error rather than a silent truncation
// (see ParseChecksums): a manifest cut mid-line could otherwise be parsed as a
// shorter, different filename than the one it really names.
const maxChecksumsManifestBytes = 4 << 20

// digestHexLen is the length of a hex-encoded SHA-256 digest.
const digestHexLen = 64

// ParseChecksums parses a sha256sum-format manifest into name -> lowercase hex
// digest. The grammar is the one coreutils writes and `sha256sum -c` reads:
//
//	<64-hex><space><mode><name>
//
// where <mode> is ' ' (text) or '*' (binary) and <name> is every remaining
// byte of the line, verbatim. The name is taken as-is rather than tokenised,
// because everything after those two separator bytes is significant: a name may
// contain spaces, may begin with '*', and may begin with "./". Treating any of
// those as syntax would file an entry under a name the manifest never published
// — i.e. hand back a digest for a different file than the one asked about.
//
// A name containing a backslash, newline or carriage return is written by
// coreutils in escaped form, marked by a backslash before the digest.
//
// Unparseable lines are skipped rather than failing the whole file: the
// manifest is generated by CI and a future extra line must not break
// verification of the entry we need. Three things are NOT tolerated, because
// each could make a name resolve to a digest published for some other file:
//
//   - a manifest with no usable entries (never read as "nothing to verify"),
//   - the same name listed twice with different digests,
//   - a manifest large enough to have been truncated by the read cap.
func ParseChecksums(r io.Reader) (map[string]string, error) {
	data, err := io.ReadAll(io.LimitReader(r, maxChecksumsManifestBytes+1))
	if err != nil {
		return nil, fmt.Errorf("read checksums: %w", err)
	}
	if len(data) > maxChecksumsManifestBytes {
		return nil, fmt.Errorf("checksums manifest exceeds %d bytes; refusing to parse a possibly truncated manifest",
			maxChecksumsManifestBytes)
	}

	out := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		// Strip only the CRLF carriage return: trailing spaces are part of the
		// name as far as sha256sum is concerned.
		line = strings.TrimSuffix(line, "\r")
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// coreutils marks an entry whose name needed escaping with a leading
		// backslash before the digest.
		escaped := strings.HasPrefix(line, `\`)
		if escaped {
			line = line[1:]
		}

		// 64 digest bytes + the 2 separator bytes + at least one name byte.
		if len(line) < digestHexLen+3 {
			continue
		}
		digest := strings.ToLower(line[:digestHexLen])
		if _, err := hex.DecodeString(digest); err != nil {
			continue
		}
		// The first separator byte is always a literal space; only the second
		// one varies (text vs binary mode). Anything else is a line
		// `sha256sum -c` would itself reject as improperly formatted.
		if line[digestHexLen] != ' ' {
			continue
		}
		if mode := line[digestHexLen+1]; mode != ' ' && mode != '*' {
			continue
		}

		name := line[digestHexLen+2:]
		if escaped {
			unescaped, ok := unescapeChecksumName(name)
			if !ok {
				// An escape sequence coreutils does not produce: the real name
				// is unknown, so skip rather than guess at it.
				continue
			}
			name = unescaped
		}

		if prev, ok := out[name]; ok && prev != digest {
			return nil, fmt.Errorf("checksums manifest lists %q twice with different digests (%s and %s); refusing to guess which one is authoritative",
				name, prev, digest)
		}
		out[name] = digest
	}

	if len(out) == 0 {
		return nil, errors.New("checksums manifest contains no usable entries")
	}
	return out, nil
}

// unescapeChecksumName reverses the coreutils escaping applied to names
// containing a backslash, newline or carriage return. It reports false for a
// sequence coreutils never emits (including a trailing lone backslash), so the
// caller can drop the line instead of inventing a name for it.
func unescapeChecksumName(name string) (string, bool) {
	var b strings.Builder
	for i := 0; i < len(name); i++ {
		if name[i] != '\\' {
			b.WriteByte(name[i])
			continue
		}
		if i+1 >= len(name) {
			return "", false
		}
		i++
		switch name[i] {
		case 'n':
			b.WriteByte('\n')
		case 'r':
			b.WriteByte('\r')
		case '\\':
			b.WriteByte('\\')
		default:
			return "", false
		}
	}
	return b.String(), true
}

// VerifyFileSHA256 hard-fails unless path hashes to wantHex.
func VerifyFileSHA256(path, wantHex string) error {
	f, err := os.Open(path) // #nosec G304 -- path is a file this process just downloaded into its own temp dir
	if err != nil {
		return fmt.Errorf("open downloaded artifact: %w", err)
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return fmt.Errorf("hash downloaded artifact: %w", err)
	}
	got := hex.EncodeToString(h.Sum(nil))
	if !strings.EqualFold(got, wantHex) {
		return fmt.Errorf("checksum mismatch for %s: manifest says %s, download is %s (nothing was installed)",
			filepath.Base(path), wantHex, got)
	}
	return nil
}
