package oauth

import (
	"bytes"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Issue #1148, round 8 — the structural check the previous seven rounds needed.
//
// Every round of this review found the same shape: a rule applied at one door
// and not at its sibling. Rounds 5, 6, 7 and 8 each fixed the doors that were
// reported and left the next one open, because nothing enumerated the doors. A
// DOOR is any function that puts a server-derived string onto a wire a client
// can read — an MCP tool response, a REST handler, an SSE payload, CLI JSON,
// diagnostics, status/stats, the tray adapter, the server edition.
//
// The scan below finds them from the SOURCE rather than from memory: every
// function in the door packages that puts a secret-bearing leaf of a server
// config / contract (or a raw config struct) into a response map, a
// contracts.* literal, or a publish sink. Each one must appear in
// serverPayloadDoors with the rule it uses — or with the reason it needs none.
//
// A new door therefore cannot be added silently: the scan finds it, the
// inventory does not have it, and this test goes red in the same edit. A door
// that is deleted or renamed fails too, so the inventory cannot rot.

// rawServerLeafDoors is the exemption table for the RAW-LEAF scan: every
// function that still puts an unredacted server leaf into a payload shape, and
// the reason that is correct there. A function NOT in this table that the scan
// finds fails the test — that is the check that would have caught rounds 5, 6,
// 7 and 8 in one go.
//
// Nothing here may be a client-facing wire carrying an unredacted credential.
// Each row is either an INTERNAL projection whose only route to a client runs
// through a named shared-rule door, a value that is not operator-supplied, or a
// payload redacted at the return statement of the same function.
var rawServerLeafDoors = map[string]string{
	// --- internal projections; redacted at the serialization boundary ---
	"internal/runtime/runtime.go:(m).GetAllServers": "the generic server map every REST/SSE consumer reads. " +
		"Masked by oauth.RedactServerSecretFields at httpapi.redactServerSecrets (GET /api/v1/servers and its " +
		"single-server children) and at runtime's /events servers.changed publisher; the MCP door builds its own " +
		"payload from redactedServerView instead. Redacting here as well would double-mask and break the " +
		"reveal_secret_headers opt-out, which is resolved at those boundaries.",
	"internal/runtime/runtime.go:(m).getAllServersLegacy":         "storage fallback of GetAllServers; same boundary, same consumers.",
	"internal/server/server.go:(m).GetAllServers":                 "the tray/legacy projection behind the same httpapi + SSE boundary.",
	"internal/server/server.go:(m).getAllServersLegacy":           "storage fallback of the above; same boundary.",
	"internal/runtime/isolation_projection.go:buildIsolationMaps": "builds the isolation sub-map of GetAllServers; masked by the shared walk in RedactServerSecretFields and by isolationValues on the MCP door.",
	"internal/management/service.go:(m).ListServers": "builds contracts.Server from the runtime projection. Redacted by " +
		"httpapi.redactServerSecrets (personal edition) and by listAdminServers (server edition); both call " +
		"oauth.RedactServerSecretFields.",

	// --- redacted at the return of the same function ---
	"internal/server/server.go:(m).GetUpstreamStats": "the per-server entries are built raw and the whole map is " +
		"handed to oauth.RedactUpstreamStats at every return, reveal-gated. Issue #1148 round 8: this is the " +
		"upstream_stats implementation that actually runs (the StateView path); round 4 masked only the " +
		"upstream.Manager fallback.",

	// --- already-redacted input; the function holds no config ---
	"cmd/mcpproxy-tray/internal/api/adapter.go:(m).GetAllServers": "re-shapes the payload the tray fetched from " +
		"GET /api/v1/servers, which the core redacted before it left the process. The tray has no config and no " +
		"second source for these fields.",
	"cmd/mcpproxy-tray/internal/api/adapter.go:(m).GetQuarantinedServers": "same already-redacted REST payload.",
	"internal/httpapi/activity.go:storageToContractActivity": "activity rows are scrubbed at WRITE " +
		"(server.scrubUpstreamTextForAudit / the audit-policy walk) and masked again on read by " +
		"Server.maskActivityPayloads before this projection is served.",
	"internal/httpapi/activity.go:storageToContractActivityForExport": "same rows, same two passes; the export route adds bodies, not new raw config leaves.",

	// --- not operator-supplied ---
	"cmd/mcpproxy/upstream_cmd.go:runUpstreamListFromConfig": "health.detail here is prose generated by " +
		"health.CalculateHealth from a fixed disconnected input; no upstream text and no config string reaches it.",
	"cmd/mcpproxy/registry_cmd.go:newRegistrySearchCmd":     "registry SEARCH results are catalogue entries fetched from a remote registry, not operator configuration.",
	"internal/runtime/runtime.go:(m).SearchRegistryServers": "same remote catalogue entries; the urls are the catalogue's.",
	"internal/upstream/core/connection_oauth.go:(m).emptyClientIDFlowError": "the url in this message is the " +
		"DISCOVERED authorization-server endpoint, not the configured upstream url.",
	"internal/upstream/core/connection_oauth.go:(m).handleOAuthAuthorization":           "discovered authorization/token endpoints in zap log fields, not a client wire.",
	"internal/upstream/core/connection_oauth.go:(m).handleOAuthAuthorizationWithResult": "same discovered endpoints.",
}

// routedDoors is the other half of the inventory: the doors that DO put a
// server-derived string on a client-facing wire and route it through the shared
// rules. The raw-leaf scan cannot see them — that is the point — so they are
// pinned here instead: the function must still exist, and its body must still
// call one of the shared rules. Deleting the redaction call from any of them
// fails this test even when the leak it would create is invisible to the scan.
var routedDoors = map[string]string{
	// MCP tool responses
	"internal/server/mcp.go:(m).handleListUpstreams": "upstream_servers list — headers/env/url/args/command from " +
		"redactedServerView, isolation + global docker_isolation from the shared walk, last_error via scrubUpstreamText",
	"internal/server/mcp.go:(m).handleAddServerFromRegistry": "add_from_registry echo — command/url from redactedServerView, args via liveRedaction.Argv",
	"internal/server/mcp.go:(m).handleListRegistries":        "list_registries — registry source url via liveRedaction.URLValue",
	"internal/server/mcp.go:(m).createDetailedErrorResponse": "MCP error payload — server_url via liveRedaction.URLValue; error/response_body/error_data scrubbed",

	// REST
	"internal/httpapi/server.go:(m).handleAddFromRegistry":      "POST registry-add echo — command/url from oauth.RedactedConfigView, args via LiveRedaction.Argv",
	"internal/httpapi/server.go:(m).handleAddRegistrySource":    "registry source echo via redactedRegistrySummary",
	"internal/httpapi/server.go:(m).handleEditRegistrySource":   "registry source echo via redactedRegistrySummary",
	"internal/httpapi/server.go:(m).handleRemoveRegistrySource": "registry source echo via redactedRegistrySummary",
	"internal/httpapi/server.go:(m).handleGetDockerStatus":      "GET /api/v1/docker/status — last_error via oauth.ScrubUpstreamText",

	// server edition
	"internal/serveredition/api/admin_handlers.go:(m).listAdminServers":   "GET /admin/servers — contracts.Server via oauth.RedactServerSecretFields; config-only fallbacks via oauth.RedactedConfigViews",
	"internal/serveredition/api/admin_handlers.go:(m).toggleSharedServer": "PUT /admin/servers/{name}/shared echo via oauth.RedactedConfigView",

	// registry catalogue + CLI + diagnostics
	"internal/runtime/runtime.go:(m).ListRegistries":                    "registry source url/servers_url via oauth.LiveRedaction.URLValue",
	"cmd/mcpproxy/upstream_cmd.go:buildImportedServersOutput":           "`upstream import` preview — url/command from oauth.RedactedConfigView, args via LiveRedaction.Argv",
	"internal/upstream/core/monitoring.go:(m).GetConnectionDiagnostics": "command/args/docker_args via oauth.LiveRedaction",
	"internal/httpapi/diagnostics_per_server.go:redactHealthDetail":     "GET /api/v1/servers/{id}/diagnostics — health.detail via oauth.ScrubUpstreamText",
	"internal/httpapi/diagnostics_per_server.go:redactDiagnosticCause":  "same route — diagnostic.cause via oauth.ScrubUpstreamText",
	"internal/oauth/serverfields.go:RedactServerSecretFields":           "the REST + SSE door onto contracts.Server; the shared rule itself",
	"internal/runtime/event_bus.go:(m).redactServerSecrets":             "/events servers.changed — oauth.RedactServerSecretFields",
	"internal/httpapi/server.go:redactServerSecretFields":               "GET /api/v1/servers and its children — oauth.RedactServerSecretFields",
	"internal/upstream/manager.go:(m).GetStats":                         "upstream_stats fallback — oauth.RedactUpstreamStatsEntry, reveal-gated",
	"internal/management/diagnostics.go:(m).Doctor":                     "doctor UpstreamErrors.ErrorMessage via oauth.ScrubUpstreamText",
}

// sharedRuleTokens are the identifiers that mean "this function routed its
// payload through the shared redaction rules".
var sharedRuleTokens = []string{
	"LiveRedaction", "liveRedaction", "auditRedaction",
	"RedactServerSecretFields", "RedactedConfigView", "RedactedConfigViews",
	"RedactUpstreamStats", "RedactUpstreamStatsEntry",
	"ScrubUpstreamText", "scrubUpstreamText", "scrubUpstreamTextForAudit",
	"redactedServerView", "redactedArgs", "redactedRegistrySummary",
	"isolationValues", "globalIsolationView", "MaskDetectedSecrets",
}

// doorPackages are the trees scanned for doors: everything that can build a
// client-facing payload out of a server config.
var doorPackages = []string{
	"internal/server",
	"internal/httpapi",
	"internal/runtime",
	"internal/management",
	"internal/upstream",
	"internal/tray",
	"internal/serveredition",
	"cmd",
}

// secretLeafFields are the field names that carry an operator-supplied,
// possibly credential-bearing string on config.ServerConfig / contracts.Server
// and their nested blocks — plus the whole-struct names, so a door that embeds
// a raw config rather than reading its leaves is caught too.
var secretLeafFields = map[string]bool{
	"URL": true, "Env": true, "Headers": true, "Args": true, "Command": true,
	"WorkingDir": true, "OAuth": true, "ExtraArgs": true, "ExtraParams": true,
	"Scopes": true, "ClientSecret": true, "LastError": true,
	"Detail": true, "Cause": true, "Isolation": true, "IsolationDefaults": true,
	"ErrorMessage": true,
	// whole-struct embeds published as a value: `m["isolation"] = cfg.DockerIsolation`
	"DockerIsolation": true,
}

// redactionCalls are the shared rules and their guards. A value handed to one
// of them is not on a wire, so the scan does not descend into the call.
var redactionCalls = map[string]bool{
	"CheckServerWriteMasks": true, "RedactedConfigView": true, "RedactedConfigViews": true,
	"RedactServerSecretFields": true, "RedactUpstreamStats": true, "RedactUpstreamStatsEntry": true,
	"ScrubUpstreamText": true, "scrubUpstreamText": true, "scrubUpstreamTextForAudit": true,
	"scrubbedConnectionStatus": true, "scrubUpstreamLines": true,
	"redactedServerView": true, "redactedServerViews": true, "redactedArgs": true,
	"redactedRegistrySummary": true, "isolationValues": true, "globalIsolationView": true,
	"redactValueWith": true, "redactActivityValue": true, "NormalizeForRedaction": true,
	"normalizeForRedaction": true, "FindMaskMarker": true, "ContainsMaskMarker": true,
	"URLValue": true, "Leaf": true, "Argv": true, "EnvValue": true, "HeaderValue": true,
	"viewField": true, "viewString": true, "viewOr": true,
}

// publishSinks are the calls that put a value on a wire.
var publishSinks = map[string]bool{
	"Marshal": true, "MarshalIndent": true, "Encode": true,
	"NewToolResultText": true, "NewToolResultError": true,
	"writeSuccess": true, "writeError": true, "writeJSON": true,
	"Publish": true, "Write": true,
}

func TestNoDoorPublishesARawServerLeaf(t *testing.T) {
	found := scanServerPayloadDoors(t)
	require.NotEmpty(t, found, "the door scan found nothing — it has stopped testing anything")

	for _, key := range sortedKeys(found) {
		reason, ok := rawServerLeafDoors[key]
		if !assert.True(t, ok,
			"NEW DOOR: %s puts an unredacted %s into a response payload.\n"+
				"Route it through the shared rules (oauth.LiveRedaction / RedactServerSecretFields / "+
				"RedactedConfigView / RedactUpstreamStats / ScrubUpstreamText), or — if it genuinely needs "+
				"none — record it in rawServerLeafDoors with the reason. Seven review rounds of issue #1148 "+
				"were one door fixed and the next one left open; this is the check that stops that.",
			key, found[key]) {
			continue
		}
		assert.NotEmpty(t, reason, "%s is exempted with no reason recorded", key)
	}

	for key := range rawServerLeafDoors {
		_, ok := found[key]
		assert.True(t, ok,
			"rawServerLeafDoors exempts %s, which the scan no longer finds. Delete the row — a stale "+
				"exemption reads as a decision that was made, about code that is gone.", key)
	}
}

// The other half of the inventory. A routed door is INVISIBLE to the raw-leaf
// scan by construction, so removing its redaction call would silently reopen
// the leak. Each one is pinned to the source: the function must still exist,
// and it must still reach a shared rule.
func TestRoutedDoors_StillCallASharedRule(t *testing.T) {
	bodies := indexFunctionBodies(t)
	for _, key := range sortedKeys(routedDoors) {
		body, ok := bodies[key]
		if !assert.True(t, ok, "routedDoors records %s, which no longer exists — delete the row or fix the name", key) {
			continue
		}
		routed := false
		for _, token := range sharedRuleTokens {
			if strings.Contains(body, token) {
				routed = true
				break
			}
		}
		assert.True(t, routed,
			"%s no longer calls any shared redaction rule.\n%s\n"+
				"It publishes server-derived strings, so removing the rule republishes them in the clear — "+
				"and the raw-leaf scan cannot see it, because the leaf reaches the payload through a local.",
			key, routedDoors[key])
	}
}

// indexFunctionBodies renders every top-level function in the door packages
// (plus internal/oauth itself) keyed the same way the scan keys them.
func indexFunctionBodies(t *testing.T) map[string]string {
	t.Helper()
	root := repoRoot(t)
	out := map[string]string{}
	for _, pkg := range append(append([]string{}, doorPackages...), "internal/oauth") {
		err := filepath.WalkDir(filepath.Join(root, pkg), func(path string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return err
			}
			fset := token.NewFileSet()
			file, perr := parser.ParseFile(fset, path, nil, 0)
			if perr != nil {
				return nil
			}
			rel, _ := filepath.Rel(root, path)
			rel = filepath.ToSlash(rel)
			for _, decl := range file.Decls {
				fn, ok := decl.(*ast.FuncDecl)
				if !ok || fn.Body == nil {
					continue
				}
				name := fn.Name.Name
				if fn.Recv != nil {
					name = "(m)." + name
				}
				var buf bytes.Buffer
				if err := printer.Fprint(&buf, fset, fn.Body); err != nil {
					continue
				}
				out[rel+":"+name] = buf.String()
			}
			return nil
		})
		require.NoError(t, err, "walking %s", pkg)
	}
	return out
}

// scanServerPayloadDoors parses the door packages and returns, per function,
// the secret-bearing leaves it puts into a response map, a contracts.* literal
// or a publish sink.
func scanServerPayloadDoors(t *testing.T) map[string]string {
	t.Helper()
	root := repoRoot(t)
	out := map[string]string{}

	for _, pkg := range doorPackages {
		dir := filepath.Join(root, pkg)
		err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
			if err != nil || d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
				return err
			}
			fset := token.NewFileSet()
			file, perr := parser.ParseFile(fset, path, nil, 0)
			if perr != nil {
				return nil
			}
			rel, _ := filepath.Rel(root, path)
			rel = filepath.ToSlash(rel)
			for _, decl := range file.Decls {
				fn, ok := decl.(*ast.FuncDecl)
				if !ok || fn.Body == nil {
					continue
				}
				if leaves := scanFuncForPublishedLeaves(fn); len(leaves) > 0 {
					name := fn.Name.Name
					if fn.Recv != nil {
						name = "(m)." + name
					}
					out[rel+":"+name] = strings.Join(leaves, ", ")
				}
			}
			return nil
		})
		require.NoError(t, err, "walking %s", pkg)
	}
	return out
}

// scanFuncForPublishedLeaves reports the secret-bearing leaves this function
// puts on a wire.
//
// Two shapes are matched. First, a SELECTOR on one of secretLeafFields used as
// a value in a map/contracts composite literal, assigned into a map index, or
// passed to a publish sink — that is `serverMap["url"] = cfg.URL`, the shape
// every leak on this issue has had. Second, a bare IDENTIFIER that was assigned
// (directly or through a range) from a raw config collection — that is
// `writeJSON(w, 200, found)` where `found` came out of `h.config.Servers`,
// which is how the server edition published the whole struct.
func scanFuncForPublishedLeaves(fn *ast.FuncDecl) []string {
	rawIdents := rawConfigIdents(fn)
	seen := map[string]bool{}
	var leaves []string

	record := func(e ast.Expr) {
		var name string
		switch x := e.(type) {
		case *ast.SelectorExpr:
			switch {
			case secretLeafFields[x.Sel.Name]:
				name = x.Sel.Name
			case isRawConfigExpr(renderExpr(x)):
				// A whole raw config collection published as a value —
				// `writeJSON(w, 200, h.config.Servers)`, the shape the server
				// edition's admin API had.
				name = "raw config collection (" + renderExpr(x) + ")"
			default:
				return
			}
		case *ast.Ident:
			if !rawIdents[x.Name] {
				return
			}
			name = "raw *config.ServerConfig (" + x.Name + ")"
		default:
			return
		}
		if seen[name] {
			return
		}
		seen[name] = true
		leaves = append(leaves, name)
	}

	ast.Inspect(fn.Body, func(n ast.Node) bool {
		switch x := n.(type) {
		case *ast.CompositeLit:
			if !isResponseLit(x) {
				return true
			}
			for _, el := range x.Elts {
				if kv, ok := el.(*ast.KeyValueExpr); ok {
					record(kv.Value)
					continue
				}
				record(el)
			}
		case *ast.AssignStmt:
			for i, lhs := range x.Lhs {
				if _, ok := lhs.(*ast.IndexExpr); ok && i < len(x.Rhs) {
					record(x.Rhs[i])
				}
			}
		case *ast.CallExpr:
			callee := calleeName(x.Fun)
			if redactionCalls[callee] {
				// The payload is BEING redacted (or checked). Its arguments are
				// not on a wire; descending would flag the fix as the defect.
				return false
			}
			if !publishSinks[callee] {
				return true
			}
			for _, arg := range x.Args {
				record(arg)
			}
		}
		return true
	})
	sort.Strings(leaves)
	return leaves
}

// rawConfigIdents returns the local identifiers that hold a RAW config server
// value: assigned from, or ranged over, an expression that renders as
// `<something-config>.Servers`, plus one hop of aliasing so
// `for _, sc := range h.config.Servers { found = sc }` taints `found` too.
//
// The rule is deliberately narrow — the rendered text of the source, not "any
// expression mentioning Config" — because a scan that flags a hundred
// plumbing functions is a scan nobody keeps green, and an inventory nobody
// keeps green is the fail-open shape this whole issue is made of.
func rawConfigIdents(fn *ast.FuncDecl) map[string]bool {
	tainted := map[string]bool{}
	isRawSource := func(e ast.Expr) bool {
		rendered := renderExpr(e)
		return isRawConfigExpr(rendered) || tainted[rendered]
	}
	for pass := 0; pass < 2; pass++ {
		ast.Inspect(fn.Body, func(n ast.Node) bool {
			switch x := n.(type) {
			case *ast.AssignStmt:
				for i, lhs := range x.Lhs {
					id, ok := lhs.(*ast.Ident)
					if !ok || i >= len(x.Rhs) {
						continue
					}
					if isRawSource(x.Rhs[i]) {
						tainted[id.Name] = true
					}
				}
			case *ast.RangeStmt:
				if x.Value != nil && isRawSource(x.X) {
					if id, ok := x.Value.(*ast.Ident); ok {
						tainted[id.Name] = true
					}
				}
			}
			return true
		})
	}
	delete(tainted, "_")
	return tainted
}

// isRawConfigExpr reports whether a rendered expression names a raw config
// server collection — `h.config.Servers`, `cfg.Servers`, `currentConfig.Servers`.
func isRawConfigExpr(rendered string) bool {
	return strings.HasSuffix(rendered, ".Servers") && strings.Contains(strings.ToLower(rendered), "config")
}

// renderExpr prints an expression back to source text.
func renderExpr(e ast.Expr) string {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, token.NewFileSet(), e); err != nil {
		return ""
	}
	return buf.String()
}

// isResponseLit reports whether a composite literal is a response payload: a
// map, a contracts.* struct, or a nested element of one.
func isResponseLit(x *ast.CompositeLit) bool {
	switch t := x.Type.(type) {
	case *ast.MapType:
		return true
	case *ast.SelectorExpr:
		id, ok := t.X.(*ast.Ident)
		return ok && id.Name == "contracts"
	case nil:
		return true
	}
	return false
}

func calleeName(fun ast.Expr) string {
	switch f := fun.(type) {
	case *ast.Ident:
		return f.Name
	case *ast.SelectorExpr:
		return f.Sel.Name
	}
	return ""
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// repoRoot walks up from this package to the directory holding go.mod.
func repoRoot(t *testing.T) string {
	t.Helper()
	dir := packageDir(t)
	for i := 0; i < 8; i++ {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		dir = filepath.Dir(dir)
	}
	t.Fatal("could not locate the repository root (no go.mod above " + packageDir(t) + ")")
	return ""
}
